name: 'Build'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    name: Build on Node ${{ matrix.node }}
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        uses: pnpm install

      - name: Build project
        run: yarn build
