name: 'Linting code'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0

      - name: Preinstall package manager
        uses: pnpm/action-setup@v2
        with:
          version: 6.24.x

      - name: Use NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Linting prettier
        run: pnpm run lint:prettier

      - name: Linting typescript
        run: pnpm run lint:typescript

      - name: Checking editorconfig
        run: pnpm run lint:editorconfig

      - name: Linting commit
        run: pnpm run commitlint -- --to '${{ github.sha }}'
